image:
  inputLayout: D:\Projects\Personal\tercer_aniversario\assets\QRLayout.png
  output: D:\Projects\Personal\tercer_aniversario\assets\QR.png

qr:
  url: https://aniversario-tres-meses.pages.dev

  size: 580
  position:
    x: 567
    y: 395

  correction: H
  colors:
    foreground: "#111827"
    background: "#FFFFFF"

  margin:
    size: 20
    cornerRadius: 18
    color: "#FFFFFF80"

  logo:
    enabled: true
    image: D:\Projects\Personal\tercer_aniversario\assets\QRIcon.png
    size: 200
    padding: 10
    backgroundColor: "#FFFFFF"